# Generated by Django 6.0 on 2025-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'admin'), (2, 'mentor'), (3, 'student')], default='student', max_length=10),
        ),
    ]
