# Generated by Django 6.0 on 2025-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_created_at_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
