# Generated by Django 6.0 on 2025-12-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_chapter_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['course', 'sequence_number']},
        ),
    ]
