# Generated by Django 6.0 on 2025-12-19 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
