# Generated by Django 6.0 on 2025-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_courseassignment_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(),
        ),
    ]
