# Generated by Django 6.0 on 2025-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_chapter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
