# Generated by Django 6.0 on 2025-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_chapter_sequence_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='sequence_number',
            field=models.PositiveIntegerField(),
        ),
    ]
